### ISSUE TITLE
Build Errors and Process on Windows

### ISSUE THREAD

**Issue by blazer2k1** [adamharrison/lite-xl-ide#1]
Something like a simple helloworld.c is throwing this error. 

Perhaps there are errors in specifying paths, where it should be escaped or doubled like `\\`. It creates an `obj` folder but there's also a build `debug` folder inserted which it didn't create related to the path issue.

Also, the completed 1 Error/Warning is also misleading when it also compiles without warning/error messages in the console.

![Untitled](https://i.imgur.com/BxSJnHVl.png)

**Comment by adamharrison** [comment]
Also, what platform are you on? Windows?

**Comment by blazer2k1** [comment]
Yes, same helloworld.c file inside a folder just like in your screenshot.

I'm using Windows 10 64bit.

**Comment by adamharrison** [comment]
Ah. you may need to supply a compiler path in that case; as I don't think gcc.exe is necessarily gonna be on your path.

I'll look into throwing up the appropriate error in that case; we'll see if that helps narrow this down.

**Comment by adamharrison** [comment]
OK. I've pushed a new fix, which *should* mostly work, based on excellent advice from @mart-on-windows in https://github.com/lite-xl/lite-xl/issues/1339.

So, I fixed the build thing, which *should* work now. The run thing should also work. 

And yeah, it turns out there's some insane shit on windows that we don't handle correctly in lite, if you pass an environment variable: 

```
If an application provides an environment block, the current directory information of the system drives is not automatically propagated to the new process. For example, there is an environment variable named =C: whose value is the current directory on drive C. An application must manually pass the current directory information to the new process. To do so, the application must explicitly create these environment variable strings, sort them alphabetically (because the system uses a sorted environment), and put them into the environment block. Typically, they will go at the front of the environment block, due to the environment block sort order.
```

So for now, I've just removed the TERM=ANSI thing, as suggested. So this *should* work now. Probably.

**Comment by blazer2k1** [comment]
@adamharrison great will check this out

>Ah. you may need to supply a compiler path in that case; as I don't think gcc.exe is necessarily gonna be on your path.

btw, MinGW is already set is in my PATH unless lite-xl and lua works like ST3 and python.

**Comment by adamharrison** [comment]
Then it *should* work out of box. In theory.
