### ISSUE TITLE
Linux GLIBC errors

### ISSUE THREAD

**Issue by sonich2401** [adamharrison/lite-xl-ide#4]
I am having troubles with the 'terminal' module and the 'debugger' module. 

How I installed:
`lpm add https://github.com/adamharrison/lite-xl-ide.git && lpm install ide --no-install-optional`

First is the terminal module, it seems to not like my GLIBC version. Sorry for the size of this image! It says that it cant find GLIBC 2.34 which is required by libterminal.x86_64-linux.so
![image](https://github.com/adamharrison/lite-xl-ide/assets/34013705/11e568bc-b4fd-4d87-a88b-b54a81368a57)
Here are the specs of my system
Ubuntu 20.04.6 LTS x86_64 Kernel: 5.15.0-88-generic
My GLIBC version is 2.31

When it comes to debugger, this is something that I have no clue about. Let me know what I can do to help with this one
![image](https://github.com/adamharrison/lite-xl-ide/assets/34013705/f366d4e5-133d-4ce0-a0f7-36c72e96954e)

**Comment by adamharrison** [comment]
Hrm. Well, the first one we can probably fix by switching to the lxl build box, which is designed to build for older systems (which should in turn work with older glibcs). I'll pencil that in for next week as something to do.

In the meantime, you can try  building the terminal plugin yourself from here: https://github.com/adamharrison/lite-xl-terminal. Just basically build it, and then stick the init.lua and the libterminal.so you get as a result of running the build script into `~/.config/lite-xl/plugins/terminal`.

re: the second issue, seems like I forgot to include the `json` library as a dependency in the manifest for `debugger`. You can fix this with `lpm install json`.

**Comment by sonich2401** [comment]
Thanks for the help. I followed your instructions on the lite-xl-terminal page and now I am getting 2 new errors as seen below. I am not sure if the 'build' plugin is a part of this as well?

![image](https://github.com/adamharrison/lite-xl-ide/assets/34013705/3086cd3f-7750-4c0e-b60a-f40d488e5f41)

**Comment by adamharrison** [comment]
Hrm. Odd. Well, the build plugin is part of ide, so it *should* be installed. Not sure why it's erroring out though. Will look into.

Re: the terminal thing, I've just pushed a small change to the build script; pull, and then try and build again. See if that works.

**Comment by adamharrison** [comment]
What's your user module look like, by the way?

**Comment by sonich2401** [comment]
The change you made to terminal fixed it! Still have the error with build tho

My user module should be the default

`-- put user settings here
-- this module will be loaded after everything else when the application starts
-- it will be automatically reloaded when saved

local core = require "core"
local keymap = require "core.keymap"
local config = require "core.config"
local style = require "core.style"

------------------------------ Themes ----------------------------------------

-- light theme:
-- core.reload_module("colors.summer")

--------------------------- Key bindings -------------------------------------

-- key binding:
-- keymap.add { ["ctrl+escape"] = "core:quit" }


------------------------------- Fonts ----------------------------------------

-- customize fonts:
-- style.font = renderer.font.load(DATADIR .. "/fonts/FiraSans-Regular.ttf", 14 * SCALE)
-- style.code_font = renderer.font.load(DATADIR .. "/fonts/JetBrainsMono-Regular.ttf", 14 * SCALE)
--
-- DATADIR is the location of the installed Lite XL Lua code, default color
-- schemes and fonts.
-- USERDIR is the location of the Lite XL configuration directory.
--
-- font names used by lite:
-- style.font          : user interface
-- style.big_font      : big text in welcome screen
-- style.icon_font     : icons
-- style.icon_big_font : toolbar icons
-- style.code_font     : code
--
-- the function to load the font accept a 3rd optional argument like:
--
-- {antialiasing="grayscale", hinting="full", bold=true, italic=true, underline=true, smoothing=true, strikethrough=true}
--
-- possible values are:
-- antialiasing: grayscale, subpixel
-- hinting: none, slight, full
-- bold: true, false
-- italic: true, false
-- underline: true, false
-- smoothing: true, false
-- strikethrough: true, false

------------------------------ Plugins ----------------------------------------

-- enable or disable plugin loading setting config entries:

-- enable plugins.trimwhitespace, otherwise it is disable by default:
-- config.plugins.trimwhitespace = true
--
-- disable detectindent, otherwise it is enabled by default
-- config.plugins.detectindent = false`

**Comment by adamharrison** [comment]
Hrm. No idea then. `build` seems to work for me. What's the output of `lpm describe`?

**Comment by sonich2401** [comment]
```warning: gitdiff_highlight stub on https://github.com/lite-xl/lite-xl-plugins.git:master has differing version from remote (0.2 vs 0.1); may lead to install being inconsistent
warning: widget stub on https://github.com/lite-xl/lite-xl-plugins.git:master has differing version from remote (0.2.1 vs 0.2); may lead to install being inconsistent
lpm run system https://github.com/adamharrison/lite-xl-ide.git:main https://github.com/lite-xl/lite-xl-plugins.git:master https://github.com/lite-xl/lite-xl-colors.git:master debugger:0.1 ide:0.1 console:0.1 exterm:0.1 language_make:0.1 language_tex:0.1 lintplus:0.2 lspkind:0.1 pdfview:0.1 search_ui:0.1 selectionhighlight:0.2 texcompile:0.1 vscode-dark:0.1 json:1.0 rainbowparen:1.0 nerdicons:1.0 terminal:1.0 settings:1.0 lsp:1.0 gitdiff_highlight:1.0 scm:1.0 smoothcaret:1.0 build:1.0 language_sh:1.0 motiontrail:1.0 lsp_c:1.0 linewrapping:1.0 language_md:1.0 reflow:1.0 tabularize:1.0 language_html:1.0 trimwhitespace:1.0 detectindent:1.0 drawwhitespace:1.0 language_lua:1.0 macro:1.0 lineguide:1.0 contextmenu:1.0 projectsearch:1.0 autocomplete:1.0 language_cpp:1.0 quote:1.0 workspace:1.0 treeview:1.0 language_js:1.0 language_c:1.0 toolbarview:1.0 language_css:1.0 autoreload:1.0 language_xml:1.0 scale:1.0 language_python:1.0 widget:1.0```

**Comment by adamharrison** [comment]
Hrm. OK, well, lpm is having some trouble running that unfortunately (my bad), so can't reproduce the issue exactly. Will look into it at some point in the near future.

**Comment by adamharrison** [comment]
OK! I've updated terminal to work on much older versions of GLIBC from lpm; so going forward, you won't need to manually build.
